variables:
  DISABLE_AUTH: "true"

stages:
  - build
  - test

build:
  stage: build
  tags:
    - ssh
  script:
    - echo "Building"
    - mvn compile

test:
  stage: test
  tags:
    - ssh
  script:
    - echo "Testing"
    - mvn clean test

